IHaveBackedUpAllMyLinstorResources: false
global:
  imagePullPolicy: IfNotPresent # empty pull policy means k8s default is used ("always" if tag == ":latest", "ifnotpresent" else)
  setSecurityContext: true # Force non-privileged containers to run as non-root users
# Dependency charts
etcd:
  enabled: false
  persistentVolume:
    enabled: true
    storage: "1Gi"
  replicas: 3 # How many instances of etcd will be added to the initial cluster.
  resources: {} # resource requirements for etcd containers
  image:
    repository: daocloud.io/piraeus/etcd
    tag: v3.4.15
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  tolerations:
  - effect: NoSchedule
    operator: Exists
# csi-snapshotter:
#   enabled: true # <- enable to add k8s snapshotting CRDs and controller. Needed for CSI snapshotting
#   image: daocloud.io/piraeus/snapshot-controller:v4.2.1
#   replicas: 3
#   resources: {} # resource requirements for the cluster snapshot controller.
stork:
  enabled: false
  storkImage: daocloud.io/piraeus/stork:2.8.2
  schedulerImage: daocloud.io/piraeus/kube-scheduler-amd64
  schedulerTag: v1.23.4
  replicas: 3
  storkResources: {} # resources requirements for the stork plugin containers
  schedulerResources: {} # resource requirements for the kube-scheduler containers
  podsecuritycontext: {}
csi:
  enabled: false
  pluginImage: daocloud.io/piraeus/piraeus-csi:v0.18.0
  csiAttacherImage: daocloud.io/piraeus/csi-attacher:v3.4.0
  csiLivenessProbeImage: daocloud.io/piraeus/livenessprobe:v2.5.0
  csiNodeDriverRegistrarImage: daocloud.io/piraeus/csi-node-driver-registrar:v2.4.0
  csiProvisionerImage: daocloud.io/piraeus/csi-provisioner:v3.1.0
  csiSnapshotterImage: daocloud.io/piraeus/csi-snapshotter:v5.0.1
  csiResizerImage: daocloud.io/piraeus/csi-resizer:v1.4.0
  csiAttacherWorkerThreads: 10
  csiProvisionerWorkerThreads: 10
  csiSnapshotterWorkerThreads: 10
  csiResizerWorkerThreads: 10
  controllerreplicas: 3
  nodeAffinity: {}
  nodeTolerations:
  - effect: NoSchedule
    operator: Exists
  controllerAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  controllerTolerations:
  - effect: NoSchedule
    operator: Exists
  enableTopology: true # k8s volume node affinity 
  resources: {}
  #   requests:
  #     cpu: 500m
  #     memory: 500Mi
  kubeletPath: /var/snap/microk8s/common/var/lib/kubelet
priorityClassName: ""
drbdRepoCred: "" # <- Specify the kubernetes secret name here
linstorSslMethod: "manual" # <- If set to 'helm' or 'cert-manager' the certificates will be generated automatically
linstorHttpsControllerSecret: "" # <- name of secret containing linstor server certificates+key. See docs/security.md
linstorHttpsClientSecret: "" # <- name of secret containing linstor client certificates+key. See docs/security.md
controllerEndpoint: "" # <- override to the generated controller endpoint. use if controller is not deployed via operator
psp:
  privilegedRole: ""
  unprivilegedRole: ""
operator:
  replicas: 3 # <- number of replicas for the operator deployment
  image: daocloud.io/piraeus/piraeus-operator:v1.8.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  tolerations:
  - effect: NoSchedule
    operator: Exists
  resources: {}
  podsecuritycontext: {}
  controller:
    enabled: true
    controllerImage: daocloud.io/piraeus/linstor-controller:v1.18.0
    dbConnectionURL: "k8s"
    luksSecret: ""
    dbCertSecret: ""
    dbUseClientCert: false
    sslSecret: ""
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
    tolerations:
    - operator: "Exists"
      effect: "NoSchedule"
    resources: {}
      # limits:
      #   cpu: 500m
      #   memory: 500Mi
    replicas: 3
    additionalEnv: []
    additionalProperties: {}
  satelliteSet:
    enabled: false
    satelliteImage: daocloud.io/piraeus/piraeus-server:v1.18.0
    storagePools: {}
    sslSecret: ""
    automaticStorageType: None
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/piraeus
              operator: In
              values:
              - "satellite"
              - "auxilary"
    tolerations:
    - operator: Exists
      effect: NoSchedule
    resources: {}
      # limits:
      #   cpu: 500m
      #   memory: 500Mi
    monitoringImage: daocloud.io/piraeus/drbd-reactor:v0.5.3
    kernelModuleInjectionImage: daocloud.io/piraeus/drbd9-bionic:v9.1.6
    kernelModuleInjectionMode: None
    kernelModuleInjectionResources: {}
    additionalEnv: []
haController:
  enabled: false
  image: daocloud.io/piraeus/piraeus-ha-controller:v0.3.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
  tolerations:
  - operator: Exists
    effect: NoSchedule
  replicas: 3
