apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-r2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: piraeus-local-lvmthin-r2