apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-pvc-r2-snapshot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: piraeus-dflt-r2
  dataSource:
    name: pvc-r2-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io