apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-pvc-r2-clone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: piraeus-dflt-r2
  dataSource:
    name: pvc-r2
    kind: PersistentVolumeClaim
    apiGroup: v1
