apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-local-zfs-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: ext4
  property.linstor.csi.linbit.com/FileSystem/Type: ext4
  property.linstor.csi.linbit.com/FileSystem/MkfsParams: -K
  mountOpts: noatime,discard
  storagePool: ZfsThin
