apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-dflt-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
