apiVersion: v1
kind: Service
metadata:
  name: sts-mysql-clone
  labels:
    app: sts-mysql-clone
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sts-mysql-clone
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-mysql-clone
spec:
  selector:
    matchLabels:
      app: sts-mysql-clone 
  serviceName: "sts-mysql-clone"
  replicas: 1
  template:
    metadata:
      labels:
        app: sts-mysql-clone
        linstor.csi.linbit.com/on-storage-lost: remove
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mysql
        image: daocloud.io/mysql
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-from-pvc-r2-clone
          
          
