apiVersion: v1
kind: Service
metadata:
  name: sts-nginx
  labels:
    app: sts-nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sts-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
spec:
  selector:
    matchLabels:
      app: sts-nginx 
  serviceName: "sts-nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: sts-nginx
        linstor.csi.linbit.com/on-storage-lost: remove
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: daocloud.io/nginx:alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-r2
          
          
